import type { Transcript } from 'assemblyai'

export const transcript = {
    id: 'fda4f563-7a7d-4b4f-8ef4-046d105d1b39',
    language_model: 'assemblyai_default',
    acoustic_model: 'assemblyai_default',
    language_code: 'en_us',
    status: 'completed',
    audio_url:
        'https://f9gwe22u0l.ufs.sh/f/1gRBBXolHQDd47o7eTPBIQm5hf0xFR9kowJpWSlMjDes1ycb',
    text: "I'm michael jordan. Stop it. Get some help.",
    words: [
        {
            text: "I'm",
            start: 640,
            end: 816,
            confidence: 0.78097,
            speaker: 'A',
        },
        {
            text: 'michael',
            start: 816,
            end: 1152,
            confidence: 0.72775,
            speaker: 'A',
        },
        {
            text: 'jordan.',
            start: 1192,
            end: 1944,
            confidence: 0.99891,
            speaker: 'A',
        },
        {
            text: 'Stop',
            start: 2072,
            end: 2360,
            confidence: 0.99973,
            speaker: 'A',
        },
        {
            text: 'it.',
            start: 2400,
            end: 3032,
            confidence: 0.99976,
            speaker: 'A',
        },
        {
            text: 'Get',
            start: 3216,
            end: 3560,
            confidence: 0.99974,
            speaker: 'A',
        },
        {
            text: 'some',
            start: 3600,
            end: 3752,
            confidence: 0.99992,
            speaker: 'A',
        },
        {
            text: 'help.',
            start: 3776,
            end: 3840,
            confidence: 0.99941,
            speaker: 'A',
        },
    ],
    utterances: [
        {
            speaker: 'A',
            text: "I'm michael jordan. Stop it. Get some help.",
            confidence: 0.9382737,
            start: 640,
            end: 3840,
            words: [
                {
                    text: "I'm",
                    start: 640,
                    end: 816,
                    confidence: 0.78097,
                    speaker: 'A',
                },
                {
                    text: 'michael',
                    start: 816,
                    end: 1152,
                    confidence: 0.72775,
                    speaker: 'A',
                },
                {
                    text: 'jordan.',
                    start: 1192,
                    end: 1944,
                    confidence: 0.99891,
                    speaker: 'A',
                },
                {
                    text: 'Stop',
                    start: 2072,
                    end: 2360,
                    confidence: 0.99973,
                    speaker: 'A',
                },
                {
                    text: 'it.',
                    start: 2400,
                    end: 3032,
                    confidence: 0.99976,
                    speaker: 'A',
                },
                {
                    text: 'Get',
                    start: 3216,
                    end: 3560,
                    confidence: 0.99974,
                    speaker: 'A',
                },
                {
                    text: 'some',
                    start: 3600,
                    end: 3752,
                    confidence: 0.99992,
                    speaker: 'A',
                },
                {
                    text: 'help.',
                    start: 3776,
                    end: 3840,
                    confidence: 0.99941,
                    speaker: 'A',
                },
            ],
        },
    ],
    confidence: 0.9382737,
    audio_duration: 5,
    punctuate: true,
    format_text: true,
    dual_channel: false,
    webhook_url: null,
    webhook_status_code: null,
    webhook_auth: false,
    webhook_auth_header_name: null,
    speed_boost: false,
    auto_highlights_result: null,
    auto_highlights: false,
    audio_start_from: null,
    audio_end_at: null,
    word_boost: [],
    boost_param: null,
    filter_profanity: false,
    redact_pii: false,
    redact_pii_audio: false,
    redact_pii_audio_quality: null,
    redact_pii_policies: null,
    speaker_labels: true,
    content_safety: false,
    iab_categories: false,
    iab_categories_result: {
        status: 'unavailable',
        results: [],
        summary: {},
    },
    language_detection: false,
    language_confidence_threshold: null,
    language_confidence: null,
    custom_spelling: null,
    throttled: false,
    auto_chapters: false,
    summarization: false,
    summary_type: null,
    summary_model: null,
    custom_topics: false,
    topics: [],
    speech_threshold: null,
    speech_model: null,
    chapters: null,
    disfluencies: false,
    entity_detection: false,
    sentiment_analysis: false,
    sentiment_analysis_results: null,
    entities: null,
    speakers_expected: null,
    summary: null,
    multichannel: null,
} satisfies Transcript
